// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package workflow_designer

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/aosanya/CodeValdCortex/internal/agency/models"
)

// WorkflowStatusBar renders the status bar for workflow designer
func WorkflowStatusBar(currentAgency *models.Agency, wf *models.Workflow) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"vscode-status-bar\"><div class=\"status-bar-left\"><div class=\"status-item\"><span class=\"icon is-small\"><i class=\"fas fa-sitemap\"></i></span> <span class=\"status-text\" x-text=\"`${workflowSteps.length} step${workflowSteps.length !== 1 ? 's' : ''}`\">0 steps</span></div><div class=\"status-item\"><span class=\"icon is-small\"><i class=\"fas fa-tasks\"></i></span> <span class=\"status-text\" x-text=\"`${workflowSteps.reduce((sum, s) => sum + s.items.length, 0)} work item${workflowSteps.reduce((sum, s) => sum + s.items.length, 0) !== 1 ? 's' : ''}`\">0 work items</span></div><div class=\"status-item\" x-show=\"saving\" x-cloak><span class=\"icon is-small has-text-warning\"><i class=\"fas fa-sync fa-spin\"></i></span> <span class=\"status-text\">Saving...</span></div></div><div class=\"status-bar-right\"><div class=\"status-item\"><span class=\"icon is-small\"><i class=\"fas fa-code-branch\"></i></span> <span class=\"status-text\" x-text=\"`v${workflowVersion || '1.0.0'}`\">v1.0.0</span></div><div class=\"status-item\"><span class=\"status-text\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(currentAgency.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/pages/workflow_designer/workflow_designer_status_bar.templ`, Line: 30, Col: 50}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
