// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package agency_designer

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// GoalsListCard renders the goals list card component with selection checkboxes
func GoalsListCard() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"box m-0 p-0\" id=\"goals-list-card\"><div class=\"level is-mobile mb-4\"><div class=\"level-left\"></div><div class=\"level-right\"><div class=\"level-item\"><button class=\"button is-small is-success\" onclick=\"showGoalEditor('add')\" id=\"add-goal-btn\" title=\"Add New Goal\"><span class=\"icon\"><i class=\"fas fa-plus\"></i></span> <span>Add</span></button></div></div></div><div id=\"goals-list\" class=\"goals-list\"><table class=\"table is-fullwidth is-striped is-hoverable\"><thead><tr><th style=\"width: 50px; text-align: center;\"><label class=\"checkbox\"><input type=\"checkbox\" id=\"select-all-goals\" onchange=\"toggleAllGoals(this.checked)\" title=\"Select/Deselect All\"></label></th><th style=\"width: 120px;\">Code</th><th>Goal Title</th><th style=\"width: 180px;\">Actions</th></tr></thead> <tbody id=\"goals-table-body\"><!-- Items will be loaded here dynamically --><tr><td colspan=\"4\" class=\"has-text-grey has-text-centered py-5\"><p><i class=\"fas fa-spinner fa-spin\"></i> Loading goals...</p></td></tr></tbody></table></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
