// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package agency_designer

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/aosanya/CodeValdCortex/internal/web/components/forms"

// WorkflowEditorCard renders the workflow editor card component
func WorkflowEditorCard() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Workflow Editor Card (Hidden by default) --><div class=\"card mb-4 is-hidden\" id=\"workflow-editor-card\"><header class=\"card-header\"><p class=\"card-header-title\"><span class=\"icon\"><i class=\"fas fa-sitemap\"></i></span> <span id=\"workflow-editor-title\">Add New Workflow</span></p><button class=\"card-header-icon button is-small is-text\" onclick=\"cancelWorkflowEdit()\" title=\"Cancel\"><span class=\"icon\"><i class=\"fas fa-times\"></i></span></button></header><div class=\"card-content\"><!-- Name Field -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = forms.TextField(forms.TextFieldConfig{
			ID:          "workflow-name-editor",
			Label:       "Workflow Name",
			HelpText:    "A clear, descriptive name for this workflow.",
			Placeholder: "e.g., User Onboarding Process",
			MaxLength:   200,
			Required:    true,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<!-- Description Field -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = forms.TextAreaField(forms.TextAreaFieldConfig{
			ID:          "workflow-description-editor",
			Label:       "Description",
			HelpText:    "Explain what this workflow does and when it should be used.",
			Placeholder: "Describe the workflow purpose and what it accomplishes...",
			Rows:        6,
			Style:       "font-family: monospace; font-size: 14px;",
			Required:    true,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<!-- Version Field -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = forms.TextField(forms.TextFieldConfig{
			ID:          "workflow-version-editor",
			Label:       "Version",
			HelpText:    "Semantic version number (major.minor.patch).",
			Placeholder: "e.g., 1.0.0",
			Value:       "1.0.0",
			MaxLength:   20,
			Required:    false,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><footer class=\"card-footer\"><div class=\"card-footer-item\"><button id=\"save-workflow-btn\" class=\"button is-small is-primary\" onclick=\"saveWorkflowFromEditor()\"><span class=\"icon\"><i class=\"fas fa-save\"></i></span> <span>Save</span></button></div><div class=\"card-footer-item\"><button class=\"button is-small\" onclick=\"cancelWorkflowEdit()\"><span class=\"icon\"><i class=\"fas fa-times\"></i></span> <span>Cancel</span></button></div></footer></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
