package auth

























































































}	Iat    int64  `json:"iat"`	Exp    int64  `json:"exp"`	Name   string `json:"name"`	Email  string `json:"email"`	UserID string `json:"user_id"`type TokenClaims struct {// TokenClaims represents the JWT claims}	User         UserResponse `json:"user"`	ExpiresIn    int          `json:"expires_in"` // seconds until access token expires	TokenType    string       `json:"token_type"`	RefreshToken string       `json:"refresh_token"`	AccessToken  string       `json:"access_token"`type AuthResponse struct {// AuthResponse represents the response after successful authentication}	RefreshToken string `json:"refresh_token" binding:"required"`type RefreshTokenRequest struct {// RefreshTokenRequest represents a token refresh request}	Password string `json:"password" binding:"required"`	Email    string `json:"email" binding:"required,email"`type LoginRequest struct {// LoginRequest represents a user login request}	Password string `json:"password" binding:"required,min=8,max=100"`	Name     string `json:"name" binding:"required,min=2,max=100"`	Email    string `json:"email" binding:"required,email"`type RegisterRequest struct {// RegisterRequest represents a user registration request}	RevokedAt *time.Time `json:"revoked_at,omitempty"`	IsRevoked bool      `json:"is_revoked"`	CreatedAt time.Time `json:"created_at"`	ExpiresAt time.Time `json:"expires_at"`	Token     string    `json:"token" binding:"required"` // Hashed refresh token	UserID    string    `json:"user_id" binding:"required"`	Rev       string    `json:"_rev,omitempty" arangodb:"_rev,omitempty"`	ID        string    `json:"_id,omitempty" arangodb:"_id,omitempty"`	Key       string    `json:"_key,omitempty" arangodb:"_key,omitempty"`type RefreshToken struct {// RefreshToken represents a refresh token for JWT token rotation}	}		IsActive:  u.IsActive,		UpdatedAt: u.UpdatedAt,		CreatedAt: u.CreatedAt,		Name:      u.Name,		Email:     u.Email,		ID:        u.ID,	return UserResponse{func (u *User) ToResponse() UserResponse {// ToResponse converts User to UserResponse (removes sensitive fields)}	IsActive  bool      `json:"is_active"`	UpdatedAt time.Time `json:"updated_at"`	CreatedAt time.Time `json:"created_at"`	Name      string    `json:"name"`	Email     string    `json:"email"`	ID        string    `json:"id"`type UserResponse struct {// UserResponse represents user data for API responses (no sensitive data)}	IsActive     bool      `json:"is_active"`	UpdatedAt    time.Time `json:"updated_at"`	CreatedAt    time.Time `json:"created_at"`	PasswordHash string    `json:"-"` // Never expose password hash in JSON	Name         string    `json:"name" binding:"required"`	Email        string    `json:"email" binding:"required,email"`	Rev          string    `json:"_rev,omitempty" arangodb:"_rev,omitempty"`	ID           string    `json:"_id,omitempty" arangodb:"_id,omitempty"`	Key          string    `json:"_key,omitempty" arangodb:"_key,omitempty"`type User struct {// User represents a user account in the system)	"time"import (package auth